/**
 * Source content for the 30-instrument library (D-010: 6 sections x 5).
 * `returns`/`tax`/`liquidity`/`risk` are deliberately qualitative — no
 * precise live numbers, per CLAUDE.md's quarterly-rate re-verification rule.
 * `rateValue`/`rateAsOf` are populated ONLY for instruments with a
 * web-search-verified, government-declared rate for the Jul-Sep 2026
 * quarter (verified 2026-07-11); every other instrument leaves both null
 * and describes its rate character in `returns` instead.
 */

export interface InstrumentSeed {
  slug: string
  category: number // 1=Equity 2=Debt 3=Gold 4=Hybrid/Guaranteed 5=Real Estate 6=Alternative
  name: string
  summary: string
  returns: string
  tax: string
  liquidity: string
  risk: string
  eligibility: string
  minInvestment: string
  rateValue: string | null
  rateAsOf: string | null
}

const VERIFIED_QUARTER = '2026-07-01' // Jul-Sep 2026 quarter start; source: Ministry of Finance small-savings notification, 2026-06-30

export const instrumentsSeedData: InstrumentSeed[] = [
  // ---------------------------------------------------------------- Equity
  {
    slug: 'equity-direct-stocks',
    category: 1,
    name: 'Direct Stocks',
    summary: 'Buying shares of individual listed companies directly on the exchange.',
    returns: 'Market-linked; can swing sharply either way over short periods. Long-term equity has historically outpaced inflation, but individual stocks carry company-specific risk on top of market risk.',
    tax: 'Gains taxed as capital gains (short-term or long-term depending on holding period) under current income tax rules; dividends are taxable as income. Rules and thresholds change with the Union Budget — verify the current rate before filing.',
    liquidity: 'High — tradeable on any market day via a demat account, subject to settlement time.',
    risk: 'High — concentrated in single-company performance; no diversification unless built manually.',
    eligibility: 'Indian residents and NRIs with a demat + trading account; requires PAN and KYC.',
    minInvestment: 'Price of one share; no fixed minimum.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'equity-active-mutual-funds',
    category: 1,
    name: 'Equity Mutual Funds (Active)',
    summary: 'Professionally managed pooled funds investing in a basket of stocks, chosen by a fund manager.',
    returns: 'Market-linked; aims to beat a benchmark index, but net-of-fees performance varies widely by fund and is not guaranteed.',
    tax: 'Capital gains tax applies on redemption, short-term or long-term depending on holding period, per current income tax rules — verify the current rate before relying on it.',
    liquidity: 'High for open-ended funds — redeemable on any business day; proceeds typically settle within a few days.',
    risk: 'Moderate to high, depending on the fund\'s stated category (large-cap, mid-cap, small-cap, sectoral).',
    eligibility: 'Indian residents, NRIs, and minors (via a guardian-operated folio); PAN and KYC required.',
    minInvestment: 'Many funds accept SIPs starting around ₹500/month or lump sums from ₹1,000 — check the specific fund.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'equity-index-funds-etfs',
    category: 1,
    name: 'Index Funds / ETFs',
    summary: 'Passively managed funds that track a market index (e.g. Nifty 50, Sensex) rather than picking stocks.',
    returns: 'Market-linked, designed to mirror the tracked index minus a small tracking error and expense ratio — no attempt to beat the market.',
    tax: 'Same capital gains treatment as other equity funds under current income tax rules — holding period determines short- vs long-term.',
    liquidity: 'High — index mutual funds redeem like any open-ended fund; ETFs trade on the exchange during market hours via a demat account.',
    risk: 'Moderate — tracks broad market risk with no single-stock or manager-selection risk, but still fully exposed to market swings.',
    eligibility: 'Indian residents, NRIs, minors via guardian folio (for the mutual fund route); ETFs need a demat account.',
    minInvestment: 'Index funds: SIPs from ~₹500/month. ETFs: price of one unit.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'equity-elss',
    category: 1,
    name: 'ELSS (Tax-Saving Equity Fund)',
    summary: 'An equity mutual fund with a mandatory 3-year lock-in, eligible for a tax deduction on investment under the old tax regime.',
    returns: 'Market-linked, similar in character to other diversified equity funds; the 3-year lock-in is the main structural difference, not the return profile.',
    tax: 'Investment eligible for deduction under Section 80C (old regime only, subject to the overall 80C cap); gains on redemption taxed as long-term capital gains (holding period is always >1 year due to the lock-in) — verify current rules, as 80C availability depends on which tax regime is chosen.',
    liquidity: 'Low for the first 3 years (hard lock-in, no early exit); high afterward, redeemable like any equity fund.',
    risk: 'Moderate to high — same market risk as other diversified equity funds.',
    eligibility: 'Indian residents; PAN and KYC required; useful only if filing under the old tax regime.',
    minInvestment: 'SIPs typically from ₹500/month.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'equity-minor-folio',
    category: 1,
    name: 'Minor\'s Equity Folio',
    summary: 'An equity mutual fund folio opened in a child\'s name, operated by a parent/guardian until the child turns 18.',
    returns: 'Same market-linked character as any equity mutual fund — the distinguishing feature is ownership and guardianship, not the return mechanism.',
    tax: 'Any income/gains are typically clubbed with the parent\'s income until the child is a minor, per current income tax clubbing provisions — verify current rules before relying on this for tax planning.',
    liquidity: 'High while operated by the guardian; the folio converts to the child\'s sole control (with fresh KYC) on turning 18.',
    risk: 'Moderate to high, same as the underlying equity fund category chosen.',
    eligibility: 'Any resident minor, folio opened and operated by a parent/legal guardian with the minor\'s birth certificate and guardian\'s KYC.',
    minInvestment: 'Same as the underlying fund — SIPs typically from ₹500/month.',
    rateValue: null,
    rateAsOf: null,
  },

  // ------------------------------------------------------------------ Debt
  {
    slug: 'debt-fixed-deposit',
    category: 2,
    name: 'Fixed Deposit (FD)',
    summary: 'A lump sum deposited with a bank or NBFC for a fixed tenure at a fixed interest rate.',
    returns: 'Fixed for the tenure, set by the individual bank/NBFC at the time of booking — rates vary by institution and tenure, so there is no single "FD rate." Check the specific bank\'s current rate card before investing.',
    tax: 'Interest is fully taxable as income at the investor\'s slab rate; TDS is deducted by the bank above a threshold.',
    liquidity: 'Moderate — premature withdrawal is usually allowed but with a penalty (typically a reduced rate).',
    risk: 'Low — principal is contractually fixed; bank FDs are insured by DICGC up to a limit per depositor per bank.',
    eligibility: 'Indian residents, NRIs (via NRE/NRO FDs), and minors (via guardian).',
    minInvestment: 'Typically ₹1,000–₹10,000 depending on the bank.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'debt-ppf',
    category: 2,
    name: 'Public Provident Fund (PPF)',
    summary: 'A long-term (15-year) government-backed savings scheme with tax-free interest and a sovereign guarantee.',
    returns: 'Government-declared rate, revised quarterly.',
    tax: 'EEE status — contribution, interest, and maturity proceeds are all tax-free under current rules (subject to Section 80C caps on the contribution side).',
    liquidity: 'Low — 15-year tenure with limited partial withdrawals allowed from the 7th year; can be extended in 5-year blocks after maturity.',
    risk: 'Very low — sovereign-guaranteed.',
    eligibility: 'Indian residents (not NRIs for new accounts); one account per person, plus accounts on behalf of minors.',
    minInvestment: '₹500/year minimum, up to ₹1.5 lakh/year maximum.',
    rateValue: '7.1',
    rateAsOf: VERIFIED_QUARTER,
  },
  {
    slug: 'debt-nsc',
    category: 2,
    name: 'National Savings Certificate (NSC)',
    summary: 'A fixed-tenure (5-year) government savings certificate available at post offices, with a fixed rate set at purchase.',
    returns: 'Government-declared rate at the time of purchase, fixed for the full 5-year tenure; revised quarterly for new purchases.',
    tax: 'Interest is taxable but deemed reinvested each year (except the final year), qualifying for Section 80C deduction in the years it\'s reinvested — verify current treatment before relying on it.',
    liquidity: 'Low — 5-year lock-in with very limited premature encashment (mainly on death of the holder).',
    risk: 'Very low — sovereign-backed.',
    eligibility: 'Indian residents; can be bought for or transferred to another eligible individual once.',
    minInvestment: '₹1,000, in multiples of ₹100 thereafter.',
    rateValue: '7.7',
    rateAsOf: VERIFIED_QUARTER,
  },
  {
    slug: 'debt-mutual-funds',
    category: 2,
    name: 'Debt Mutual Funds',
    summary: 'Pooled funds investing in bonds, government securities, and money-market instruments rather than equities.',
    returns: 'Linked to prevailing interest rates and the credit quality of the underlying instruments; generally steadier than equity funds but not risk-free.',
    tax: 'Gains are taxed as per current income tax rules for debt funds, which have changed in recent years — verify the current treatment (indexation benefits have been withdrawn for most debt funds bought after a certain date) before relying on it.',
    liquidity: 'High — most are open-ended and redeemable on any business day, though some have an exit load for early redemption.',
    risk: 'Low to moderate, depending on the fund\'s credit quality and duration — long-duration and credit-risk funds carry meaningfully more risk than liquid/overnight funds.',
    eligibility: 'Indian residents, NRIs, minors via guardian folio; PAN and KYC required.',
    minInvestment: 'SIPs typically from ₹500/month; lump sums from ₹1,000.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'debt-epf-gpf',
    category: 2,
    name: 'Provident Fund (EPF / GPF)',
    summary: 'Retirement savings deducted from salary — EPF for private-sector employees, GPF for government employees under the old pension framework.',
    returns: 'Government-declared rate, notified annually (EPF confirmed at 8.25% for FY2025-26); GPF is set separately by the Department of Economic Affairs and has historically tracked close to the EPF rate, but should be verified independently rather than assumed identical.',
    tax: 'EEE status for EPF in most cases (contribution, interest, and withdrawal after 5 years of continuous service are tax-free, subject to conditions); GPF has its own long-standing tax-free treatment for government employees. Verify current rules for early withdrawal, which can trigger tax.',
    liquidity: 'Low while employed — full withdrawal is normally only on retirement/resignation after a gap, though partial withdrawals are allowed for specific life events.',
    risk: 'Very low — both are government-backed retirement schemes.',
    eligibility: 'EPF: salaried employees at eligible establishments (employer-linked, automatic for most). GPF: government employees under the old pension scheme only.',
    minInvestment: 'Determined by employee/employer contribution rules — not a voluntary lump-sum product.',
    rateValue: '8.25',
    rateAsOf: '2025-04-01',
  },

  // ------------------------------------------------------------------ Gold
  {
    slug: 'gold-physical',
    category: 3,
    name: 'Physical Gold',
    summary: 'Jewellery, coins, or bars held directly — the most traditional form of gold ownership in Indian households.',
    returns: 'Tracks the market price of gold; jewellery returns are further reduced by making charges and wastage, which are not recovered on resale.',
    tax: 'Capital gains tax applies on sale, short-term or long-term depending on holding period, per current income tax rules.',
    liquidity: 'Moderate — sellable at a jeweller or through gold-loan/buyback schemes, but making charges are typically not recovered and purity checks can affect the price realized.',
    risk: 'Low market risk (tracks gold price) but real-world risks around storage, theft, and purity/making-charge loss on resale.',
    eligibility: 'Anyone; no KYC needed for purchase below certain cash-transaction thresholds, though large purchases require PAN.',
    minInvestment: 'Price of the smallest coin/unit a seller offers — no fixed minimum.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'gold-sovereign-bonds',
    category: 3,
    name: 'Sovereign Gold Bonds (SGB)',
    summary: 'Government-issued bonds denominated in grams of gold, paying a small fixed annual interest on top of the gold price.',
    returns: 'Tracks the market price of gold at maturity/redemption, plus a small fixed annual interest paid twice a year.',
    tax: 'Capital gains on redemption at maturity are exempt from tax for individuals under current rules; the periodic interest is taxable as income. Verify current treatment, and note the government has not issued new SGB tranches continuously — availability varies.',
    liquidity: 'Low to moderate — 8-year tenure with an exit window from year 5, or tradeable on the stock exchange (though secondary-market liquidity can be thin).',
    risk: 'Very low credit risk (sovereign-backed); still fully exposed to gold price movements.',
    eligibility: 'Indian residents; issued in periodic tranches by the RBI when open — not always available for fresh purchase.',
    minInvestment: '1 gram equivalent per bond; maximum per person per year is capped.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'gold-etf',
    category: 3,
    name: 'Gold ETF',
    summary: 'An exchange-traded fund backed by physical gold, tradeable in small units through a demat account.',
    returns: 'Tracks the market price of gold minus a small expense ratio and tracking error — no making charges, unlike jewellery.',
    tax: 'Capital gains tax applies on sale, per current income tax rules for exchange-traded fund units.',
    liquidity: 'High — tradeable on the exchange during market hours like a stock.',
    risk: 'Low market risk beyond the gold price itself; no purity or storage risk since it is dematerialized.',
    eligibility: 'Indian residents, NRIs with a demat + trading account.',
    minInvestment: 'Price of one unit (a small fraction of a gram).',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'gold-digital',
    category: 3,
    name: 'Digital Gold',
    summary: 'Gold bought in small fractional amounts through an app or platform, held in a vault by the provider on the buyer\'s behalf.',
    returns: 'Tracks the market price of gold; typically has a spread between buy and sell price set by the platform.',
    tax: 'Treated similarly to physical gold for capital gains purposes on sale, per current income tax rules.',
    liquidity: 'Moderate — sellable back to the platform, though most platforms require conversion to physical gold or full sale after a holding period (there is no long-term "storage as-is" guarantee on some platforms).',
    risk: 'Depends on the platform\'s own credibility and vaulting/insurance arrangements — not government-regulated in the same way as SGBs or gold ETFs.',
    eligibility: 'Anyone with a smartphone and payment method; typically no KYC for small amounts.',
    minInvestment: 'As low as ₹1–₹10 on some platforms.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'gold-mutual-fund',
    category: 3,
    name: 'Gold Mutual Fund (Fund of Funds)',
    summary: 'A mutual fund that invests in gold ETF units, allowing SIP-style gold accumulation without a demat account.',
    returns: 'Tracks the market price of gold minus fund expenses, similar to a gold ETF but with an added layer of fund management cost.',
    tax: 'Capital gains tax applies on redemption, per current income tax rules for fund-of-funds structures.',
    liquidity: 'High — redeemable like any open-ended mutual fund on any business day.',
    risk: 'Low market risk beyond the gold price itself.',
    eligibility: 'Indian residents, NRIs, minors via guardian folio; no demat account required.',
    minInvestment: 'SIPs typically from ₹500/month.',
    rateValue: null,
    rateAsOf: null,
  },

  // ---------------------------------------------------- Hybrid/Guaranteed
  {
    slug: 'hybrid-ssy',
    category: 4,
    name: 'Sukanya Samriddhi Yojana (SSY)',
    summary: 'A government savings scheme exclusively for a girl child, offering one of the highest guaranteed rates among small savings schemes.',
    returns: 'Government-declared rate, revised quarterly — currently among the highest of all small savings schemes.',
    tax: 'EEE status — contribution, interest, and maturity proceeds are all tax-free under current rules, subject to Section 80C caps on the contribution side.',
    liquidity: 'Low — matures 21 years from account opening or on the girl\'s marriage after age 18; limited partial withdrawal allowed for higher education after she turns 18.',
    risk: 'Very low — sovereign-guaranteed.',
    eligibility: 'A resident Indian girl child under 10 years old at account opening; account operated by a parent/guardian; maximum two accounts per family (exceptions for twins).',
    minInvestment: '₹250/year minimum, up to ₹1.5 lakh/year maximum.',
    rateValue: '8.2',
    rateAsOf: VERIFIED_QUARTER,
  },
  {
    slug: 'hybrid-kvp',
    category: 4,
    name: 'Kisan Vikas Patra (KVP)',
    summary: 'A government savings certificate structured to double the invested amount over a fixed, rate-dependent tenure.',
    returns: 'Government-declared rate at time of purchase, fixed for the full tenure (currently structured to double the investment in a defined number of months).',
    tax: 'Interest is fully taxable as income at the investor\'s slab rate; no Section 80C benefit on the contribution.',
    liquidity: 'Low for the first 2.5 years (lock-in); premature encashment allowed after that period.',
    risk: 'Very low — sovereign-backed.',
    eligibility: 'Indian residents; available at post offices and select banks.',
    minInvestment: '₹1,000, in multiples of ₹100 thereafter.',
    rateValue: '7.5',
    rateAsOf: VERIFIED_QUARTER,
  },
  {
    slug: 'hybrid-nps',
    category: 4,
    name: 'National Pension System (NPS)',
    summary: 'A government-regulated, market-linked retirement scheme with a mix of equity, corporate debt, and government-bond fund choices.',
    returns: 'Market-linked; return depends on the investor\'s chosen asset allocation across equity/corporate debt/government bonds and is not guaranteed.',
    tax: 'Contributions eligible for deduction under Section 80CCD (including an additional amount beyond the 80C cap under current rules); a portion of the maturity corpus is tax-free, the rest is taxed depending on how it is withdrawn (lump sum vs. mandatory annuity) — verify current rules, which have been revised over time.',
    liquidity: 'Low until retirement age — partial withdrawal is allowed only for specific defined reasons; a portion of the corpus must go into an annuity at exit.',
    risk: 'Low to moderate to high depending on the chosen equity allocation — NPS caps the maximum equity exposure allowed.',
    eligibility: 'Indian residents (including NRIs) aged 18-70; a separate NPS Vatsalya variant exists for minors, operated by a guardian.',
    minInvestment: '₹500 per contribution / ₹1,000 per year minimum to keep the account active.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'hybrid-balanced-funds',
    category: 4,
    name: 'Balanced / Hybrid Mutual Funds',
    summary: 'Mutual funds that hold a mix of equity and debt in a single scheme, aiming for a smoother ride than pure equity.',
    returns: 'Market-linked; moderated by the debt portion, so typically less volatile than a pure equity fund but with correspondingly lower long-term upside.',
    tax: 'Tax treatment depends on the fund\'s actual equity allocation at any point — funds with equity allocation above a set threshold are taxed as equity funds, others as debt funds, under current income tax rules. Verify the specific fund\'s classification.',
    liquidity: 'High — most are open-ended and redeemable on any business day.',
    risk: 'Moderate — lower than pure equity funds, higher than pure debt funds.',
    eligibility: 'Indian residents, NRIs, minors via guardian folio; PAN and KYC required.',
    minInvestment: 'SIPs typically from ₹500/month.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'hybrid-traditional-insurance',
    category: 4,
    name: 'Traditional Life Insurance / Endowment Plans',
    summary: 'Insurance policies that combine a life cover with a savings/maturity payout, common examples include LIC endowment and money-back plans.',
    returns: 'Typically low relative to pure market-linked instruments once the cost of the embedded insurance is accounted for — the bundled structure makes the effective investment return hard to isolate and compare against pure investment products.',
    tax: 'Maturity proceeds are tax-free under current rules only if the premium-to-cover ratio meets specified conditions — high-premium policies bought after certain dates may not qualify. Verify current rules for the specific policy.',
    liquidity: 'Low — surrendering early typically returns significantly less than premiums paid, especially in the first several years.',
    risk: 'Low investment risk (insurer-guaranteed payouts) but low transparency into the actual return being earned, since insurance cost and investment return are bundled together.',
    eligibility: 'Indian residents meeting the insurer\'s underwriting criteria (age, health).',
    minInvestment: 'Varies by policy and insurer; typically requires a multi-year premium commitment.',
    rateValue: null,
    rateAsOf: null,
  },

  // -------------------------------------------------------------- Real Estate
  {
    slug: 'realestate-residential',
    category: 5,
    name: 'Residential Property',
    summary: 'A completed flat or house, bought either to live in or to rent out.',
    returns: 'Combination of rental yield (typically modest as a percentage of property value in most Indian cities) and price appreciation, which varies hugely by location and market cycle.',
    tax: 'Rental income is taxable after standard deductions; capital gains on sale are taxed as short- or long-term per current income tax rules, with reinvestment exemptions available under specific sections.',
    liquidity: 'Low — selling a property can take months, involves significant transaction costs (stamp duty, brokerage, registration).',
    risk: 'Moderate to high — highly dependent on location, developer/builder track record (for under-construction), and local market cycles; not easily diversified.',
    eligibility: 'Indian residents and NRIs (subject to RBI rules for NRIs); requires clear title verification before purchase.',
    minInvestment: 'Full property price, typically financed partly via a home loan.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'realestate-land',
    category: 5,
    name: 'Land / Plots',
    summary: 'Undeveloped or semi-developed land, bought for future construction or as a standalone investment.',
    returns: 'Purely price appreciation-driven (no rental income unless leased for other use); highly dependent on location, upcoming infrastructure, and local development plans.',
    tax: 'Capital gains tax applies on sale, short- or long-term per current income tax rules; agricultural land has separate, often more favourable, tax treatment subject to specific conditions.',
    liquidity: 'Low — often the least liquid real estate category; title disputes and unclear conversion status (agricultural vs. non-agricultural) are common practical risks.',
    risk: 'High — title/encroachment risk, zoning and land-use restriction risk, and dependence on speculative local development are all real, non-diversifiable risks specific to land.',
    eligibility: 'Indian residents; NRIs face additional restrictions on agricultural land purchase under FEMA rules.',
    minInvestment: 'Full plot price; varies enormously by location.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'realestate-reits',
    category: 5,
    name: 'REITs (Real Estate Investment Trusts)',
    summary: 'A listed vehicle that owns income-generating commercial real estate (mainly office space), letting investors buy in via the stock exchange.',
    returns: 'Combination of a mandatory-distribution income yield (REITs must distribute most of their net distributable cash flow) and unit price movement, both linked to the performance of the underlying commercial properties.',
    tax: 'Distribution components (dividend, interest, capital repayment) are taxed differently from each other under current income tax rules; unit price gains on sale are taxed as capital gains.',
    liquidity: 'High — REIT units trade on the stock exchange during market hours like a stock.',
    risk: 'Moderate — diversified across multiple properties/tenants (lower single-asset risk than owning one property directly) but still exposed to commercial real estate cycles.',
    eligibility: 'Indian residents, NRIs with a demat + trading account.',
    minInvestment: 'Price of one unit — significantly lower entry point than buying physical property.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'realestate-underconstruction',
    category: 5,
    name: 'Under-Construction Property',
    summary: 'A property booked before completion, typically at a lower price than a ready-to-move unit, with payments linked to construction milestones.',
    returns: 'Potential for gains if the property price rises before completion, but returns are entirely dependent on the project actually being delivered.',
    tax: 'GST applies on under-construction purchases (unlike ready-to-move properties with a completion certificate) under current rules; capital gains rules apply on eventual resale.',
    liquidity: 'Very low — cannot be occupied or fully monetized until possession; resale before possession is legally and practically harder.',
    risk: 'High — construction delay, developer default, and project non-completion are real, well-documented risks in the Indian residential market.',
    eligibility: 'Indian residents and NRIs; requires verifying the project\'s RERA (Real Estate Regulatory Authority) registration before booking.',
    minInvestment: 'Booking amount plus milestone-linked payments; varies by project.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'realestate-commercial',
    category: 5,
    name: 'Commercial Property',
    summary: 'Office, retail, or warehouse space bought directly (not via a REIT), typically for rental income.',
    returns: 'Rental yields are generally higher than residential property, but returns are concentrated in a single tenant/location with limited diversification.',
    tax: 'Rental income is taxable after standard deductions; capital gains on sale taxed per current income tax rules; GST may apply on rental income above a threshold.',
    liquidity: 'Low — higher ticket size than residential property makes it a smaller buyer pool and typically slower to sell.',
    risk: 'High — single-tenant vacancy risk, larger capital commitment, and less standardized market pricing than residential property.',
    eligibility: 'Indian residents and NRIs (subject to RBI rules); typically requires larger capital or commercial financing.',
    minInvestment: 'Full property price — commercial units are generally more expensive per square foot than comparable residential space.',
    rateValue: null,
    rateAsOf: null,
  },

  // -------------------------------------------------------------- Alternative
  {
    slug: 'alternative-crypto',
    category: 6,
    name: 'Cryptocurrency',
    summary: 'Digital assets like Bitcoin or Ethereum, bought and held via an exchange or personal wallet — not regulated as a security or currency in India.',
    returns: 'Highly volatile and speculative; price swings of large percentages within days are common, in either direction.',
    tax: 'Gains are taxed at a flat rate under current rules specific to "virtual digital assets" (distinct from regular capital gains rules), with no offsetting of losses against other income allowed — verify current rules, as VDA taxation is a relatively new and still-evolving area.',
    liquidity: 'High on major exchanges for major coins, but can drop sharply for smaller/less-traded tokens; exchange counterparty risk is a real consideration.',
    risk: 'Very high — no underlying cash flows, regulatory status is still evolving in India, and custody/security (wallet loss, exchange failure) is the investor\'s own responsibility.',
    eligibility: 'Anyone with a bank account and a registered exchange KYC; no age restriction beyond the exchange\'s own terms.',
    minInvestment: 'Fractional purchases possible — as low as a few hundred rupees on most exchanges.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'alternative-p2p-lending',
    category: 6,
    name: 'Peer-to-Peer (P2P) Lending',
    summary: 'Lending money directly to individual or small-business borrowers through an RBI-registered P2P lending platform, earning interest.',
    returns: 'Interest rate is set per loan/borrower risk grade by the platform; higher than typical FDs to compensate for meaningfully higher default risk.',
    tax: 'Interest earned is taxable as income at the investor\'s slab rate, similar to FD interest, per current income tax rules.',
    liquidity: 'Low — money is locked into individual loan tenures; early exit generally isn\'t available, and platforms cap how much of a portfolio can go to a single borrower to manage default risk.',
    risk: 'High — borrower default risk is real and not government-insured; returns depend heavily on the platform\'s underwriting quality and the investor\'s own diversification across many small loans.',
    eligibility: 'Indian residents; platforms must be RBI-registered NBFC-P2P entities — verify registration before investing.',
    minInvestment: 'Typically a few hundred to a few thousand rupees per loan, spread across many loans.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'alternative-aif',
    category: 6,
    name: 'Alternative Investment Funds (AIFs)',
    summary: 'SEBI-registered pooled investment vehicles (private equity, venture capital, hedge-fund-style strategies) aimed at sophisticated, high-net-worth investors.',
    returns: 'Highly strategy-dependent — ranges from private-equity-style long-horizon growth bets to hedge-fund-style market-neutral strategies; not standardized or easily comparable across funds.',
    tax: 'Tax treatment depends on the AIF category (I, II, or III) under current SEBI/income tax rules, each taxed differently — verify the specific fund\'s category and pass-through status before investing.',
    liquidity: 'Very low — typically multi-year lock-ins with limited or no exit before the fund\'s defined term ends.',
    risk: 'High — strategy, manager, and illiquidity risk are all significant; minimum ticket sizes are set deliberately high to restrict access to investors who can absorb losses.',
    eligibility: 'Indian residents and NRIs meeting SEBI\'s accredited/sophisticated investor criteria; not open to the general retail public.',
    minInvestment: '₹1 crore minimum under current SEBI rules (lower for accredited investors in specific cases) — verify the current threshold.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'alternative-chit-funds',
    category: 6,
    name: 'Chit Funds',
    summary: 'A traditional Indian rotating savings scheme where a fixed group of members contributes a fixed amount periodically, and one member takes the full pot each cycle (by bid or lot).',
    returns: 'Depends on when in the cycle a member takes the pot — early takers effectively borrow at a cost, late takers earn a return; the actual yield is a function of the group\'s bidding behaviour, not a fixed rate.',
    tax: 'Any dividend/income earned from a chit is taxable as income under current rules; treatment of the "discount" for early withdrawal has its own nuances — verify with a tax advisor for the specific chit structure.',
    liquidity: 'Low — funds are only accessible when the member wins their turn (by bid or draw), or via specific exit terms defined by the registered chit fund company.',
    risk: 'Moderate to high — heavily dependent on the organizer\'s solvency and registration status; only chits registered under the Chit Funds Act with a licensed foreman carry regulatory protection.',
    eligibility: 'Indian residents; only join chits registered under the Chit Funds Act, 1982, run by a licensed foreman.',
    minInvestment: 'Set by the specific chit\'s periodic contribution amount — varies widely by scheme size.',
    rateValue: null,
    rateAsOf: null,
  },
  {
    slug: 'alternative-unlisted-shares',
    category: 6,
    name: 'Unlisted / Pre-IPO Shares',
    summary: 'Shares of companies not yet listed on a stock exchange, bought through private placement, employee stock options, or specialized unlisted-share dealers.',
    returns: 'Highly speculative — potential for large gains if the company eventually lists successfully or is acquired, but no guarantee of either happening, and no public market price in the meantime.',
    tax: 'Capital gains tax applies on eventual sale, with a different holding-period threshold for long-term classification than listed shares, per current income tax rules.',
    liquidity: 'Very low — no public exchange to sell on; exit depends on finding a private buyer, a future IPO, or a company buyback.',
    risk: 'Very high — valuation is opaque and dealer-quoted rather than market-determined, information disclosure is far weaker than for listed companies, and total loss is a real possibility if the company fails.',
    eligibility: 'Indian residents; typically requires going through a specialized unlisted-share broker/dealer, or access via ESOPs.',
    minInvestment: 'Varies by dealer and company; often requires buying in board-lot-like minimums set by the seller.',
    rateValue: null,
    rateAsOf: null,
  },
]
