import { z } from 'zod'

/**
 * The one shape the server is allowed to know about for encrypted tables.
 *
 * The whole point of this module is negative: there is deliberately NO schema
 * anywhere on the server that accepts an amount, a name, a date of birth or an
 * asset class for `households`, `family_members`, `holdings` or `protection`.
 * A client cannot send one even by mistake, because every schema below is
 * `.strict()` and unknown keys are rejected outright rather than dropped.
 *
 * Mirrors server/lib/household-keys.ts's conventions: a locally declared
 * algorithm label (no import from the browser crypto module), base64url-only
 * blobs with explicit bounds, and `.strict()` objects.
 */

/** Row cipher label. Mirrors `ROW_ALG` in src/lib/crypto/row.ts; kept local so the server never imports browser crypto. */
export const SUPPORTED_ROW_ALG = 'AES-256-GCM'

/**
 * Ciphertext bound. Row plaintext is JSON, padded to 256-byte blocks, so the
 * largest legitimate row (a holding with a 1000-character note) lands well
 * under 2 KiB of ciphertext; 16 KiB of base64url leaves generous headroom for
 * a future field without letting the table double as a file store.
 */
export const MAX_CIPHERTEXT_CHARS = 16_384
/** A 96-bit IV is 16 base64url characters; the bound only has to stop abuse. */
export const MAX_IV_CHARS = 64

/** Postgres `integer` ceiling — also the ceiling `buildAad` enforces on the AAD version. */
const MAX_VERSION = 0x7fffffff

// Base64url alphabet only (RFC 4648 §5, unpadded). Anything outside it — spaces,
// '+', '/', '=', punctuation — is rejected, so these columns cannot be used to
// stash something that merely looks like plaintext.
const base64urlBlob = (max: number) =>
  z
    .string()
    .min(8)
    .max(max)
    .regex(/^[A-Za-z0-9_-]+$/, 'must be unpadded base64url')

const envelopeShape = {
  ciphertext: base64urlBlob(MAX_CIPHERTEXT_CHARS),
  iv: base64urlBlob(MAX_IV_CHARS),
  alg: z.literal(SUPPORTED_ROW_ALG),
}

/**
 * Row ids are generated by the client, not the database.
 *
 * WHY: the AAD every ciphertext is bound to includes the row id, so the client
 * has to know the id *before* it can encrypt. A server-assigned id would force
 * either a second round trip (leaving a blank row behind if it fails) or
 * dropping `rowId` from the AAD, which is what stops a ciphertext being moved
 * between rows. A v4 UUID from the client is the cheaper, safer trade: the
 * household is still resolved server-side from the session, so a client can
 * pick an id but never pick whose data it lands next to — at worst it collides
 * with an existing primary key and the insert fails.
 */
export const rowIdSchema = z.string().uuid()

/** Foreign key to `family_members`. Readable on purpose — rows are grouped by member without unlocking. */
export const memberIdSchema = z.string().uuid()

/** `{ ciphertext, iv, alg }` and nothing else. */
export const encryptedCreateSchema = z.object(envelopeShape).strict()

/** `{ ciphertext, iv, alg }` plus the version the client read. */
export const encryptedUpdateSchema = z
  .object({
    ...envelopeShape,
    expectedVersion: z.number().int().min(1).max(MAX_VERSION - 1),
  })
  .strict()

/** Create body for a row that hangs off a family member (holdings, protection). */
export const memberScopedCreateSchema = z
  .object({ ...envelopeShape, id: rowIdSchema, memberId: memberIdSchema })
  .strict()

/** Create body for a row that hangs off the household alone (households, family_members). */
export const householdScopedCreateSchema = z.object({ ...envelopeShape, id: rowIdSchema }).strict()

export type EncryptedEnvelope = z.infer<typeof encryptedCreateSchema>
export type EncryptedUpdate = z.infer<typeof encryptedUpdateSchema>
export type MemberScopedCreate = z.infer<typeof memberScopedCreateSchema>
export type HouseholdScopedCreate = z.infer<typeof householdScopedCreateSchema>

/**
 * The envelope as it comes back out of the database.
 *
 * All three blob columns are nullable: rows written before encryption existed
 * have `ciphertext === null`. That is a real, expected state — "not yet
 * encrypted" — and is reported to the client as such rather than being
 * treated as corruption or hidden behind a non-null assertion.
 */
export interface StoredEnvelope {
  ciphertext: string | null
  iv: string | null
  alg: string | null
  version: number
}

/** The outcome of a version-conditional update. */
export type UpdateOutcome<T> =
  | { status: 'updated'; row: T }
  | { status: 'not_found' }
  /** The row exists but its stored version is not the one the client read. */
  | { status: 'conflict' }
